language: ruby
sudo: false
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head

gemfile:
  - gemfiles/activesupport_2.3_LTS.gemfile
  - gemfiles/activesupport_3.gemfile
  - gemfiles/activesupport_4.gemfile
  - gemfiles/activesupport_5.gemfile
  - gemfiles/activesupport_6.gemfile

before_install:
  - yes | gem update --system --force
  - gem install bundler